# Generated by Django 2.0.5 on 2018-07-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_datetime', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=100)),
                ('event_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('photo_url', models.TextField()),
                ('interest', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meatup.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_events', to='meatup.User'),
        ),
    ]
