# Generated by Django 2.0.5 on 2018-07-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meatup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='pic.jpg', upload_to=''),
        ),
    ]
