# Generated by Django 2.0.5 on 2018-07-30 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meatup', '0002_remove_event_attendees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='owner',
        ),
    ]
