# Generated by Django 2.0.5 on 2018-08-01 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meatup', '0003_auto_20180731_2153'),
        ('meatup', '0003_remove_event_owner'),
    ]

    operations = [
    ]
