# Generated by Django 2.0.5 on 2018-08-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meatup', '0004_auto_20180801_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
