# Generated by Django 2.0.5 on 2018-08-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meatup', '0004_merge_20180801_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meatup.User'),
        ),
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_events', to='meatup.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(choices=[('pic1', 'Pic1')], max_length=1, null=True),
        ),
    ]
